# Generated by Django 5.0.7 on 2024-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('language', models.CharField(max_length=45)),
                ('genre_1', models.CharField(max_length=45)),
                ('watched', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('extra_info', models.CharField(max_length=100)),
            ],
        ),
    ]
